### ISSUE TITLE
Arrow keys not working properly in pager (e.g. less)

### ISSUE THREAD

**Issue by hellow554** [kumavale/sisterm#6] opened 2020-10-26 15:41 UTC
When I connect via the serial line to a linux device and open something in a pager (e.g. journalctl which uses less by default), I can't use the arrow keys to navigate left, right up or down.

In the normal bash, it works flawlessly, but inside of less it doesn't work.
It works however with tera term, so I guess there's something wrong.

Funny enough, <kbd>Page Up</kbd> and <kbd>Page Down</kbd> work, as well as <kbd>j</kbd>/<kbd>k</kbd>

**Comment by kumavale** [comment] 2020-10-26 18:40
It is known issue. But I don't know the cause.  
I feel like this question is relevant... [https://vi.stackexchange.com/questions/15324/up-arrow-key-code-why-a-becomes-oa](https://vi.stackexchange.com/questions/15324/up-arrow-key-code-why-a-becomes-oa)

**Comment by kumavale** [comment] 2020-10-27 05:17
Check if the received string contains these and set the flag  

```rust
/* repl.rs */
if output.contains("\x1B[?1h") {
    DECCKM = true;
} else if output.contains("\x1B[?1l") {
    DECCKM = false;
}
```
And then
```rust
/* getch.rs */
0x48 => {
    if DECCKM {
        Ok(Key::Other(vec![ b'\x1B', b'O', b'A' ]))
    } else {
        Ok(Key::Up)
    }
},
0x50 => {
    if DECCKM {
        Ok(Key::Other(vec![ b'\x1B', b'O', b'B' ]))
    } else {
        Ok(Key::Down)
    }
},
0x4D => {
    if DECCKM {
        Ok(Key::Other(vec![ b'\x1B', b'O', b'C' ]))
    } else {
        Ok(Key::Right)
    }
},
0x4B => {
    if DECCKM {
        Ok(Key::Other(vec![ b'\x1B', b'O', b'D' ]))
    } else {
        Ok(Key::Left)
    }
},
```

By doing this, the arrow keys will work properly even with less and vim.  
But I want to find a better way...  

### References
- [https://ttssh2.osdn.jp/manual/4/en/usage/tips/appkeypad.html](https://ttssh2.osdn.jp/manual/4/en/usage/tips/appkeypad.html)
- [https://www.vt100.net/docs/vt510-rm/DECCKM.html](https://www.vt100.net/docs/vt510-rm/DECCKM.html)

**Comment by kumavale** [comment] 2020-10-28 03:07
I understand the cause!  
This issue will be fixed soon.

**Comment by kumavale** [comment] 2020-10-31 09:31
v2.4.0 released  
It works properly by setting the appropriate terminal type.

**Closed by kumavale** 2020-10-31 09:31 UTC
